import 'package:flutter/material.dart';

class AppStrings {
  static String t(BuildContext context, String key, {Map<String, String>? params}) {
    return forLocale(Localizations.localeOf(context).languageCode, key, params: params);
  }

  static String forLocale(String languageCode, String key, {Map<String, String>? params}) {
    var text = (_strings[languageCode] ?? _strings['en']!)[key] ?? key;
    params?.forEach((k, v) => text = text.replaceAll('{$k}', v));
    return text;
  }

  static const _strings = {
    'vi': {
      'appName': 'Bước Nhẹ',
      'appTagline': 'Đếm bước chân mềm mại mỗi ngày',
      'home': 'Hôm nay',
      'stats': 'Thống kê',
      'history': 'Lịch sử',
      'reminders': 'Nhắc nhở',
      'settings': 'Cài đặt',
      'today': 'Hôm nay',
      'steps': 'bước',
      'stepsToday': 'Bước hôm nay',
      'dailyGoal': 'Mục tiêu ngày',
      'goalReached': 'Đã đạt mục tiêu!',
      'keepWalking': 'Tiếp tục đi bộ nhé!',
      'almostThere': 'Sắp đạt mục tiêu rồi!',
      'startWalking': 'Bắt đầu di chuyển để đếm bước',
      'distance': 'Quãng đường',
      'calories': 'Calories',
      'km': 'km',
      'kcal': 'kcal',
      'weeklyStats': 'Tuần này',
      'average': 'Trung bình',
      'streak': 'Chuỗi ngày',
      'days': 'ngày',
      'perDay': '/ngày',
      'thisWeek': '7 ngày qua',
      'totalSteps': 'Tổng bước',
      'bestDay': 'Ngày tốt nhất',
      'monthlyOverview': 'Tổng quan tháng',
      'noData': 'Chưa có dữ liệu',
      'noDataSub': 'Đi bộ để bắt đầu đếm bước',
      'sensorOff': 'Cảm biến chưa sẵn sàng',
      'sensorOffSub': 'Cấp quyền hoạt động để đếm bước tự động',
      'grantPermission': 'Cấp quyền',
      'enableReminder': 'Bật nhắc nhở',
      'reminderInterval': 'Tần suất nhắc',
      'everyHours': 'Mỗi {h} giờ',
      'reminderTimes': 'Lịch nhắc nhở',
      'goalReminder': 'Nhắc đạt mục tiêu',
      'goalReminderDesc': 'Thông báo khi hoàn thành mục tiêu bước chân',
      'theme': 'Giao diện',
      'light': 'Sáng',
      'dark': 'Tối',
      'language': 'Ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'stepGoal': 'Mục tiêu bước chân',
      'widget': 'Widget màn hình chính',
      'widgetDesc': 'Hiển thị bước chân hôm nay trên màn hình chính',
      'widgetHint': 'Thêm widget Bước Nhẹ từ màn hình chính',
      'about': 'Giới thiệu',
      'aboutDesc': 'Ứng dụng đếm bước chân nhẹ nhàng — dùng cảm biến có sẵn, không cần GPS.',
      'version': 'Phiên bản',
      'onboardingTitle': 'Chào mừng đến Bước Nhẹ',
      'onboardingSubtitle': 'Theo dõi bước chân mỗi ngày, sống khỏe mà không cần GPS.',
      'onboardingFeature1': 'Đếm bước tự động bằng cảm biến điện thoại',
      'onboardingFeature2': 'Biểu đồ tuần và lịch sử đẹp mắt',
      'onboardingFeature3': 'Widget màn hình chính, dữ liệu riêng tư',
      'start': 'Bắt đầu',
      'skip': 'Bỏ qua',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'mon': 'T2',
      'tue': 'T3',
      'wed': 'T4',
      'thu': 'T5',
      'fri': 'T6',
      'sat': 'T7',
      'sun': 'CN',
      'copyright': '© 2026 Bước Nhẹ',
      'privacyPolicy': 'Chính sách riêng tư',
      'privacyPolicyTitle': 'Chính sách riêng tư',
      'privacyPolicyBody':
          'Cập nhật: 10/06/2026\n\n'
          'Bước Nhẹ chỉ lưu dữ liệu bước chân trên thiết bị của bạn.\n'
          'Chúng tôi thu thập:\n'
          '• Số bước chân hàng ngày\n'
          '• Mục tiêu và cài đặt giao diện\n\n'
          'Ứng dụng dùng cảm biến chuyển động (accelerometer) để đếm bước — không dùng GPS, không theo dõi vị trí. '
          'Chúng tôi không thu thập, truyền hay bán dữ liệu cá nhân. '
          'Nếu bật nhắc nhở, ứng dụng chỉ lên lịch thông báo cục bộ trên thiết bị.\n\n'
          'Dữ liệu sẽ bị xóa khi bạn gỡ cài đặt hoặc xóa dữ liệu ứng dụng.',
      'goalAchieved': 'Chúc mừng! Bạn đã đạt {goal} bước hôm nay! 🎉',
      'walkReminder': 'Đi bộ thôi! 👟',
      'walkReminderBody': 'Hãy vận động thêm để đạt mục tiêu bước chân hôm nay.',
      'progress': '{pct}% mục tiêu',
    },
    'en': {
      'appName': 'Gentle Steps',
      'appTagline': 'Soft daily step tracking',
      'home': 'Today',
      'stats': 'Stats',
      'history': 'History',
      'reminders': 'Reminders',
      'settings': 'Settings',
      'today': 'Today',
      'steps': 'steps',
      'stepsToday': "Today's steps",
      'dailyGoal': 'Daily goal',
      'goalReached': 'Goal reached!',
      'keepWalking': 'Keep walking!',
      'almostThere': 'Almost there!',
      'startWalking': 'Start moving to count steps',
      'distance': 'Distance',
      'calories': 'Calories',
      'km': 'km',
      'kcal': 'kcal',
      'weeklyStats': 'This week',
      'average': 'Average',
      'streak': 'Streak',
      'days': 'days',
      'perDay': '/day',
      'thisWeek': 'Last 7 days',
      'totalSteps': 'Total steps',
      'bestDay': 'Best day',
      'monthlyOverview': 'Monthly overview',
      'noData': 'No data yet',
      'noDataSub': 'Take a walk to start counting',
      'sensorOff': 'Sensor not ready',
      'sensorOffSub': 'Grant activity permission to count steps automatically',
      'grantPermission': 'Grant permission',
      'enableReminder': 'Enable reminders',
      'reminderInterval': 'Reminder interval',
      'everyHours': 'Every {h} hours',
      'reminderTimes': 'Reminder schedule',
      'goalReminder': 'Goal achievement alert',
      'goalReminderDesc': 'Notify when you complete your daily step goal',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'stepGoal': 'Step goal',
      'widget': 'Home screen widget',
      'widgetDesc': 'Show today\'s steps on your home screen',
      'widgetHint': 'Add the Gentle Steps widget from your home screen',
      'about': 'About',
      'aboutDesc': 'A gentle step counter — uses built-in sensors, no GPS needed.',
      'version': 'Version',
      'onboardingTitle': 'Welcome to Gentle Steps',
      'onboardingSubtitle': 'Track your daily steps softly — no GPS required.',
      'onboardingFeature1': 'Auto step counting with phone sensors',
      'onboardingFeature2': 'Beautiful weekly charts and history',
      'onboardingFeature3': 'Home widget, private on-device data',
      'start': 'Get started',
      'skip': 'Skip',
      'save': 'Save',
      'cancel': 'Cancel',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'copyright': '© 2026 Gentle Steps',
      'privacyPolicy': 'Privacy Policy',
      'privacyPolicyTitle': 'Privacy Policy',
      'privacyPolicyBody':
          'Last updated: June 10, 2026\n\n'
          'Gentle Steps stores your step data locally on your device only.\n'
          'We collect:\n'
          '• Daily step counts\n'
          '• Goal and appearance settings\n\n'
          'The app uses motion sensors (accelerometer) to count steps — no GPS, no location tracking. '
          'We do not collect, transmit, or sell your personal data. '
          'If you enable reminders, the app schedules local notifications on your device.\n\n'
          'All data is removed when you uninstall the app or clear its storage.',
      'goalAchieved': 'Congrats! You hit {goal} steps today! 🎉',
      'walkReminder': 'Time to walk! 👟',
      'walkReminderBody': 'Move a bit more to reach your step goal today.',
      'progress': '{pct}% of goal',
    },
  };
}
